### ISSUE TITLE
blocked and crash after commit and forcefull rollback

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#110]
```
017-08-30 17:12:07; cppcms_http, info: POST /strus/document/insert/lexspider (http_api.cpp:251)
2017-08-30 17:12:08; strusWebService, info: insert(lexspider, 4425cf52-29d5-4e77-b164-742afff59c93, bgeru2k-16.10.2003_4P.117_2003, 0.703486s) (document.cpp:239)
2017-08-30 17:12:08; cppcms_http, info: POST /strus/document/insert/lexspider (http_api.cpp:251)
2017-08-30 17:12:08; strusWebService, info: insert(lexspider, 4425cf52-29d5-4e77-b164-742afff59c93, bgeru2k-04.03.2003_4P.262_2002, 0.238887s) (document.cpp:239)
2017-08-30 17:12:08; cppcms_http, info: POST /strus/transaction/commit/lexspider (http_api.cpp:251)
2017-08-30 17:12:38; cppcms_http, info: POST /strus/document/insert/lexspider (http_api.cpp:251)
2017-08-30 17:13:08; cppcms_http, info: POST /strus/document/insert/lexspider (http_api.cpp:251)
2017-08-30 17:13:38; cppcms_http, info: POST /strus/document/insert/lexspider (http_api.cpp:251)
2017-08-30 17:14:08; cppcms_http, info: POST /strus/document/insert/lexspider (http_api.cpp:251)
2017-08-30 17:14:10; strusWebService, warning: forcing rollback on idle transaction '4425cf52-29d5-4e77-b164-742afff59c93' (age: 122s) (strusIndexContext.cpp:69)
```

everything is normal, the a commit happens. then I see 3 insert request which just hang, finally
the rollback is the cleanup mechanism in the webservice cleaning up a stale transaction.

**Comment by andreasbaumann** [comment]
I personally think this is the Java feeder causing trouble an miscalculating transaction identifiers:

```
2017-08-31 10:24:56; cppcms_http, info: POST /strus/transaction/commit/lexspider_insert (http_api.cpp:251)
2017-08-31 10:25:26; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 10:25:56; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 10:25:58; strusWebService, info: commit(lexspider_insert, 91965877-2166-4939-b696-c62e4af4f2d1, 1000, 61.832783s) (transaction.cpp:228)
2017-08-31 10:25:58; strusWebService, error: Referencing illegal transaction, no begin transaction seen before (master.cpp:101)
2017-08-31 10:25:58; strusWebService, error: Referencing illegal transaction, no begin transaction seen before (master.cpp:101)
2017-08-31 10:25:58; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 10:25:58; strusWebService, error: Referencing illegal transaction, no begin transaction seen before (master.cpp:101)
```

**Comment by andreasbaumann** [comment]
Did the experiment twice now, twice same behaviour but with differnent number of documents in
the recovered index:
```
curl -s http://localhost:8081/strus/index/stats/lexspider
{"execution_time":0.000174113,"result":"ok","stats":{"nof_docs":35663}}
[root@test01 lexspider]# curl -s http://localhost:8081/strus/index/stats/lexspider_insert
{"execution_time":0.000166353,"result":"ok","stats":{"nof_docs":37663}}
```

**Comment by andreasbaumann** [comment]
```
2017-08-31 19:27:01; cppcms_http, info: POST /strus/transaction/commit/lexspider_insert (http_api.cpp:251)
2017-08-31 19:27:31; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 19:28:01; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 19:28:31; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 19:29:01; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251
```

Those http_api.cpp indicate, that the request was seen by cppcms, but all other messages are missing
(with document.cpp in the log messages). The last log message of an operation on the index is:

```
2017-08-31 19:27:01; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 19:27:01; strusWebService, info: insert(lexspider_insert, 8c751056-6fcc-400c-8088-c5c2a1473ccb, bgeru2k-29.09.2004_I_416_04, 0.368507s) (document.cpp:239)
```

The I see a commit:

```
2017-08-31 19:27:01; cppcms_http, info: POST /strus/transaction/commit/lexspider_insert (http_api.cpp:251)
```

Apparently the feeder doesn't wait for the commit to finish and executes up to 4 new inserts:

```
2017-08-31 19:27:31; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 19:28:01; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 19:28:31; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
2017-08-31 19:29:01; cppcms_http, info: POST /strus/document/insert/lexspider_insert (http_api.cpp:251)
```

This is the size of the applicaiton pool/thread pool + 1.

So we mus investigate the Java code calling the commits..

**Comment by andreasbaumann** [comment]
After recovering and restarting the struswebService and feeding again, it works.
So I start to wonder if it has something to do with even longer commits and the merge problem
in leveldb I'm experiencing in the other project?

**Comment by andreasbaumann** [comment]
It's the Java code (not strusJavaAPI, the one using it) doing all kind of crazy stuff to come up with
a transaction identifier. I see:

```
net.strus.service.impl.ws.WebService$WebServiceException: Referencing illegal transaction, no begin trans
action seen before
        at net.strus.service.impl.ws.WebService.insertDocument(WebService.java:278)
        at com.eurospider.search.query.lexspider.StrusManager.indexDocument(StrusManager.java:174)
        at com.eurospider.search.query.lexspider.StrusIndexAdapter.indexDocument(StrusIndexAdapter.java:111)
        at com.eurospider.search.query.lexspider.StrusIndexAdapter.index(StrusIndexAdapter.java:97)
        at com.eurospider.search.query.indexadapter.impl.BranchIndexAdapter.index(BranchIndexAdapter.java:73)
        at com.eurospider.search.query.manager.IndexManager.index(IndexManager.java:50)
        at com.eurospider.search.query.servlets.IndexServlet.handleRequest(IndexServlet.java:72)
        at com.eurospider.search.query.servlets.IndexServlet.doPost(IndexServlet.java:54)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:401)
        at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:766)
        at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:450)
        at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:230)
        at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
```

Should be rethought and redone.

Not a bug in the strusWebService..
