### ISSUE TITLE
running out of file descriptors

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#46]
```
net.strus.service.impl.ws.WebService$WebServiceException: leveldb error: IO error: /var/lib/strusWebService/storage/aza/190642.ldb: Too many open files
    at net.strus.service.impl.ws.WebService.query(WebService.java:415)
    at com.eurospider.og.webui.servlet.StrusService.search(StrusService.java:129)
    at com.eurospider.og.webui.servlet.SearchServlet.search(SearchServlet.java:197)
    at com.eurospider.og.webui.servlet.SearchServlet.doSearch(SearchServlet.java:175)
    at com.eurospider.og.webui.servlet.SearchServlet.doGet(SearchServlet.java:108)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
    at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by andreasbaumann** [comment]
Seems to happen on an index which has recenently been updated only.

**Comment by andreasbaumann** [comment]
When restarting the service, leveldb seems to reorganize some data on disk after a big update.
Before that the index seems to be non-querieable.

**Comment by andreasbaumann** [comment]
Mutliple parallel indexes in one service. max_nof_files respected when opening the index?
Can we work around the problem by setting ulimit for filedescriptors to max_nof_files * nof_indexes?

**Comment by andreasbaumann** [comment]
Doing a simple wget with N queries (with the same query) shows the described behaviour.

The system opens more and more ldb files:

```
Jul  4 14:42 192044.ldb
-rw-rw-r--  1 struswebservice struswebservice 2114919 Jul  4 14:42 192045.ldb
-rw-rw-r--  1 struswebservice struswebservice 2118259 Jul  4 14:42 192046.ldb
-rw-rw-r--  1 struswebservice struswebservice 2118319 Jul  4 14:42 192047.ldb
-rw-rw-r--  1 struswebservice struswebservice 2103745 Jul  4 14:42 192048.ldb
-rw-rw-r--  1 struswebservice struswebservice 2143617 Jul  4 14:42 192049.ldb
```

why?

**Comment by andreasbaumann** [comment]
Originally 100 files, after stressing with queries:

```
ls -al /var/lib/strusWebService/storage/index | wc -l
1757
```

same after stopping.

After starting:

```
ls -al /var/lib/strusWebService/storage/aza | wc -l
1757
```

They are sticky.

**Comment by andreasbaumann** [comment]
Doesn't happen in fresh index or on other indexes. I think, it's an unfinished transaction which
caused the index to corrupt somehow.

**Comment by andreasbaumann** [comment]
Could be a side-effect of #47.

**Comment by andreasbaumann** [comment]
#47 is fixed, so closing also this bug. Never seen again happening.
