### ISSUE TITLE
segfault while inserting and issueing a close index in the middle of a transaction

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#53]
```
#0  0x00007f817620ea94 in ?? () from /usr/lib/libleveldb.so.1
#1  0x00007f817620ec84 in leveldb::MemTable::KeyComparator::operator()(char const*, char const*) const
    () from /usr/lib/libleveldb.so.1
#2  0x00007f817620f2b0 in leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::FindGreaterOrEqual(char const* const&, leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::Node**) const () from /usr/lib/libleveldb.so.1
#3  0x00007f817620f32b in leveldb::SkipList<char const*, leveldb::MemTable::KeyComparator>::Insert(char const* const&) () from /usr/lib/libleveldb.so.1
#4  0x00007f817620effc in leveldb::MemTable::Add(unsigned long, leveldb::ValueType, leveldb::Slice const&, leveldb::Slice const&) () from /usr/lib/libleveldb.so.1
#5  0x00007f817621f930 in leveldb::WriteBatch::Iterate(leveldb::WriteBatch::Handler*) const ()
   from /usr/lib/libleveldb.so.1
#6  0x00007f817621fb94 in leveldb::WriteBatchInternal::InsertInto(leveldb::WriteBatch const*, leveldb::MemTable*) () from /usr/lib/libleveldb.so.1
#7  0x00007f8176202e4d in leveldb::DBImpl::Write(leveldb::WriteOptions const&, leveldb::WriteBatch*)
    () from /usr/lib/libleveldb.so.1
#8  0x00007f817a027163 in strus::DatabaseTransaction::commit (this=0x7f815417eb30)
    at /data/work/strus/strus/src/database_leveldb/databaseTransaction.cpp:95
#9  0x00007f817a455b72 in strus::StorageTransaction::commit (this=0x7f81545fdd10)
    at /data/work/strus/strus/src/storage/storageTransaction.cpp:330
#10 0x00000000004358f2 in apps::document::insert_cmd (this=this@entry=0x2072e48, name="rrb", id="", 
    docid_in_url=docid_in_url@entry=false) at /data/work/strus/strusWebService/src/document.cpp:221
#11 0x0000000000436370 in apps::document::insert_payload_cmd (this=0x2072e48, name="rrb")
    at /data/work/strus/strusWebService/src/document.cpp:60
#12 0x0000000000438db9 in cppcms::url_dispatcher::binder1<apps::document>::operator() (
    p1="\020I1o\201\177\000\000\003\000\000\000\000\000\000\000rrb\000\000\000\000\000\001\000\000\000\000\000\000\000\060I1o\201\177\000\000\003\000\000\000\000\000\000\000rrb\000\201\177\000\000\060?\a\002\000\000\000\000\300I1o\201\177\000\000\240I1o\201\177\000\000\003\000\000\000\000\000\000\000\200I1o\201\177\000\000\320^\a\002\000\000\000\000\nyxz\201\177\000\000\025\000\000\000\000\000\000\000\060\215C\000\000\000\000\000\003\000\000\000\000\000\000\000\020\177.f\201\177\000\000\020\177.f\201\177\000\000\000\000\000\000\000\000\000\000\260I1o\201\177\000\000\003\000\000\000\000\000\000\000rrb\000\000\000\000\000\360L\a\002\000\000\000\000\320I1o\201\177\000\000"..., this=0x2075ed8)
    at /usr/include/cppcms/url_dispatcher.h:233
#13 booster::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>::callable_impl<void, cppcms::url_dispatcher::binder1<apps::document> >::call(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x2075ed0, a1=...)
    at /usr/include/booster/function.h:178
#14 0x00007f817a78790a in ?? () from /usr/lib/libcppcms.so.1
#15 0x00007f817a783a0a in cppcms::url_dispatcher::dispatch(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#16 0x00007f817a74336f in cppcms::application::main(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#17 0x00007f817a77779e in cppcms::http::context::dispatch(booster::intrusive_ptr<cppcms::application>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) ()
#18 0x00007f817a77950e in booster::function<void ()>::callable_impl<void, cppcms_boost::_bi::bind_t<void, void (*)(booster::intrusive_ptr<cppcms::application>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool), cppcms_boost::_bi::list3<cppcms_boost::_bi::value<booster::intrusive_ptr<cppcms::application> >, cppcms_boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, cppcms_boost::_bi::value<bool> > > >::call() ()
   from /usr/lib/libcppcms.so.1
#19 0x00007f817a77b5d1 in cppcms::impl::thread_pool::worker() () from /usr/lib/libcppcms.so.1
#20 0x00007f817ab890ea in booster_thread_func () from /usr/lib/libbooster.so.0
#21 0x00007f8177a28484 in start_thread () from /usr/lib/libpthread.so.0
#22 0x00007f8177d256dd in clone () from /usr/lib/libc.so.6

```

**Comment by andreasbaumann** [comment]
Applied conservative locking, should hold, see #61 .
