### ISSUE TITLE
segfault in long transaction

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#54]
```
#0  0x00007f0f56c6e155 in strus::KeyMap::getOrCreate (this=this@entry=0x7f0f400019b8, name="696-2009")
    at /data/work/strus/strus/src/storage/keyMap.cpp:67
#1  0x00007f0f56c4e2bc in strus::StorageTransaction::createDocument (this=0x7f0f400012d0, 
    docid="696-2009") at /data/work/strus/strus/src/storage/storageTransaction.cpp:220
#2  0x0000000000435418 in apps::document::insert_cmd (this=this@entry=0x16f64a8, name="rrb", id="", 
    docid_in_url=docid_in_url@entry=false) at /data/work/strus/strusWebService/src/document.cpp:162
#3  0x00000000004365a0 in apps::document::insert_payload_cmd (this=0x16f64a8, name="rrb")
    at /data/work/strus/strusWebService/src/document.cpp:60
#4  0x0000000000438fe9 in cppcms::url_dispatcher::binder1<apps::document>::operator() (p1="", 
    this=0x16f8dd8) at /usr/include/cppcms/url_dispatcher.h:233
#5  booster::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>::callable_impl<void, cppcms::url_dispatcher::binder1<apps::document> >::call(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x16f8dd0, a1=...)
    at /usr/include/booster/function.h:178
#6  0x00007f0f56f8090a in ?? () from /usr/lib/libcppcms.so.1
#7  0x00007f0f56f7ca0a in cppcms::url_dispatcher::dispatch(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#8  0x00007f0f56f3c36f in cppcms::application::main(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#9  0x00007f0f56f7079e in cppcms::http::context::dispatch(booster::intrusive_ptr<cppcms::application>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool) ()
   from /usr/lib/libcppcms.so.1
---Type <return> to continue, or q <return> to quit---
#10 0x00007f0f56f7250e in booster::function<void ()>::callable_impl<void, cppcms_boost::_bi::bind_t<void, void (*)(booster::intrusive_ptr<cppcms::application>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool), cppcms_boost::_bi::list3<cppcms_boost::_bi::value<booster::intrusive_ptr<cppcms::application> >, cppcms_boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, cppcms_boost::_bi::value<bool> > > >::call() ()
   from /usr/lib/libcppcms.so.1
#11 0x00007f0f56f745d1 in cppcms::impl::thread_pool::worker() () from /usr/lib/libcppcms.so.1
#12 0x00007f0f573820ea in booster_thread_func () from /usr/lib/libbooster.so.0
#13 0x00007f0f54221484 in start_thread () from /usr/lib/libpthread.so.0
#14 0x00007f0f5451e6dd in clone () from /usr/lib/libc.so.6
```

**Comment by andreasbaumann** [comment]
```
#1  0x00007f0f56c4e2bc in strus::StorageTransaction::createDocument (this=0x7f0f400012d0, 
    docid="696-2009") at /data/work/strus/strus/src/storage/storageTransaction.cpp:220
220                     Index dn = m_docIdMap.getOrCreate( docid);
(gdb) p docid
$1 = "696-2009"
(gdb) up
#2  0x0000000000435418 in apps::document::insert_cmd (this=this@entry=0x16f64a8, name="rrb", id="", 
    docid_in_url=docid_in_url@entry=false) at /data/work/strus/strusWebService/src/document.cpp:162
162             strus::StorageDocumentInterface *doc = transaction->createDocument( docid );
(gdb) down
#1  0x00007f0f56c4e2bc in strus::StorageTransaction::createDocument (this=0x7f0f400012d0, 
    docid="696-2009") at /data/work/strus/strus/src/storage/storageTransaction.cpp:220
220                     Index dn = m_docIdMap.getOrCreate( docid);
(gdb) down
#0  0x00007f0f56c6e155 in strus::KeyMap::getOrCreate (this=this@entry=0x7f0f400019b8, name="696-2009")
    at /data/work/strus/strus/src/storage/keyMap.cpp:67
67                      rt = m_allocator->getOrCreate( name);
(gdb) p name
$2 = "696-2009"
(gdb) p m_allocator 
$3 = (strus::KeyAllocatorInterface *) 0x7f0f40000f40
(gdb) p *m_allocator 
$4 = {_vptr.KeyAllocatorInterface = 0x27a00000273, m_immediate = 127}
```

**Comment by andreasbaumann** [comment]
Applied conservative locking, should hold, see #61 .
