### ISSUE TITLE
swapping indexes while inserting kills the service

### ISSUE THREAD

**Issue by andreasbaumann** [Eurospider/strusWebService#68]
```
strusWebService: tpp.c:84: __pthread_tpp_change_priority: Assertion `new_prio == -1 || (new_prio >= fifo_min_prio && new_prio <= fifo_max_prio)' failed.
Abort (core dumped)
```

trace is:

```
(gdb) bt
#0  0x00007f630bc8004f in raise () from /usr/lib/libc.so.6
#1  0x00007f630bc8147a in abort () from /usr/lib/libc.so.6
#2  0x00007f630bc78ea7 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007f630bc78f52 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007f630ba41d69 in __pthread_tpp_change_priority () from /usr/lib/libpthread.so.0
#5  0x00007f630ba3961c in __pthread_mutex_lock_full () from /usr/lib/libpthread.so.0
#6  0x00007f630e45a958 in boost::posix::pthread_mutex_lock (m=<optimized out>)
    at /usr/include/boost/thread/pthread/mutex.hpp:62
#7  boost::mutex::lock (this=<optimized out>) at /usr/include/boost/thread/pthread/mutex.hpp:116
#8  boost::unique_lock<boost::mutex>::lock (this=<synthetic pointer>)
    at /usr/include/boost/thread/lock_types.hpp:346
#9  boost::unique_lock<boost::mutex>::unique_lock (m_=..., this=<synthetic pointer>)
    at /usr/include/boost/thread/lock_types.hpp:124
#10 strus::StorageClient::allocTypenoImm (this=0x7f62d0380180, name="title")
    at /data/work/strus/strus/src/storage/storageClient.cpp:572
#11 0x00007f630e4882e8 in strus::KeyMap::getOrCreate (this=this@entry=0x7f62e00014e8, name="title")
    at /data/work/strus/strus/src/storage/keyMap.cpp:67
#12 0x00007f630e46a333 in strus::StorageTransaction::getOrCreateTermType (this=0x7f62e0000fb0, name=...)
    at /data/work/strus/strus/src/storage/storageTransaction.cpp:77
#13 0x00007f630e49cfad in strus::StorageDocument::addForwardIndexTerm (this=0x7f62d01da120, type_=..., 
    value_="Grundwasserrecht", position_=@0x7f6300b0e550: 1)
    at /data/work/strus/strus/src/storage/storageDocument.cpp:75
---Type <return> to continue, or q <return> to quit--- 
#14 0x00000000004373c7 in apps::document::insert_cmd (this=this@entry=0xc33c08, name="rrb", id="", docid_in_url=docid_in_url@entry=false)
    at /data/work/strus/strusWebService/src/document.cpp:183
#15 0x00000000004383c0 in apps::document::insert_payload_cmd (this=0xc33c08, name="rrb") at /data/work/strus/strusWebService/src/document.cpp:60
#16 0x00000000004389e9 in cppcms::url_dispatcher::binder1<apps::document>::operator() (p1="", this=0x154a418) at /usr/include/cppcms/url_dispatcher.h:233
#17 booster::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)>::callable_impl<void, cppcms::url_dispatcher::binder1<apps::document> >::call(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x154a410, a1=...) at /usr/include/booster/function.h:178
#18 0x00007f630e79a90a in ?? () from /usr/lib/libcppcms.so.1
#19 0x00007f630e796a0a in cppcms::url_dispatcher::dispatch(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#20 0x00007f630e75636f in cppcms::application::main(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () from /usr/lib/libcppcms.so.1
#21 0x00007f630e78a79e in cppcms::http::context::dispatch(booster::intrusive_ptr<cppcms::application>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)
    () from /usr/lib/libcppcms.so.1
#22 0x00007f630e78c50e in booster::function<void ()>::callable_impl<void, cppcms_boost::_bi::bind_t<void, void (*)(booster::intrusive_ptr<cppcms::application>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool), cppcms_boost::_bi::list3<cppcms_boost::_bi::value<booster::intrusive_ptr<cppcms::application> >, cppcms_boost::_bi::value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, cppcms_boost::_bi::value<bool> > > >::call() () from /usr/lib/libcppcms.so.1
#23 0x00007f630e78e5d1 in cppcms::impl::thread_pool::worker() () from /usr/lib/libcppcms.so.1
#24 0x00007f630eb9c0ea in booster_thread_func () from /usr/lib/libbooster.so.0
#25 0x00007f630ba37454 in start_thread () from /usr/lib/libpthread.so.0
#26 0x00007f630bd357df in clone () from /usr/lib/libc.so.6
```

This is the only thread running:

```
(gdb) info threads
  Id   Target Id         Frame 
* 1    Thread 0x7f6300b0f700 (LWP 28685) 0x00007f630bc8004f in raise () from /usr/lib/libc.so.6
  2    Thread 0x7f6304b17700 (LWP 28677) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  3    Thread 0x7f6304316700 (LWP 28678) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  4    Thread 0x7f6303b15700 (LWP 28679) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  5    Thread 0x7f6303314700 (LWP 28680) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  6    Thread 0x7f6302b13700 (LWP 28681) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  7    Thread 0x7f6302312700 (LWP 28682) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  8    Thread 0x7f6301b11700 (LWP 28683) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  9    Thread 0x7f6301310700 (LWP 28684) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  10   Thread 0x7f630030e700 (LWP 28686) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  11   Thread 0x7f62feb0c700 (LWP 28792) 0x00007f630ba3d10f in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
  12   Thread 0x7f630ef9f740 (LWP 28676) 0x00007f630bd35dd3 in epoll_wait () from /usr/lib/libc.so.6
```

**Comment by andreasbaumann** [comment]
Is the mutex by any chance called recurively?

http://stackoverflow.com/questions/21825291/threading-issues
https://sourceware.org/ml/libc-help/2008-05/msg00071.html

**Comment by andreasbaumann** [comment]
Applied conservative locking, should hold, see #61 .
